# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JARVIS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1985, 1016)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroud = QtWidgets.QLabel(self.centralwidget)
        self.backgroud.setGeometry(QtCore.QRect(0, 0, 1991, 1181))
        self.backgroud.setAutoFillBackground(False)
        self.backgroud.setText("")
        self.backgroud.setPixmap(QtGui.QPixmap("GUI images/background.gif"))
        self.backgroud.setScaledContents(True)
        self.backgroud.setObjectName("backgroud")
        self.shutengine = QtWidgets.QPushButton(self.centralwidget)
        self.shutengine.setGeometry(QtCore.QRect(1660, 930, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.shutengine.setFont(font)
        self.shutengine.setAutoFillBackground(False)
        self.shutengine.setStyleSheet("background-color: transparent;\n"
"font: 81 14pt \"Rockwell Extra Bold\";\n"
"color: rgb(255, 0, 0);")
        self.shutengine.setObjectName("shutengine")
        self.initialising = QtWidgets.QLabel(self.centralwidget)
        self.initialising.setGeometry(QtCore.QRect(10, -30, 591, 171))
        self.initialising.setText("")
        self.initialising.setPixmap(QtGui.QPixmap("GUI images/system initialising.gif"))
        self.initialising.setScaledContents(True)
        self.initialising.setObjectName("initialising")
        self.voice = QtWidgets.QLabel(self.centralwidget)
        self.voice.setGeometry(QtCore.QRect(40, 230, 681, 381))
        self.voice.setAutoFillBackground(False)
        self.voice.setStyleSheet("background:transparent;\n"
"border:none;")
        self.voice.setText("")
        self.voice.setPixmap(QtGui.QPixmap("GUI images/tumblr_nrqm32yH3W1r6xm5co1_640.gif"))
        self.voice.setScaledContents(True)
        self.voice.setObjectName("voice")
        self.datetimebox = QtWidgets.QLabel(self.centralwidget)
        self.datetimebox.setGeometry(QtCore.QRect(610, 10, 351, 111))
        self.datetimebox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.datetimebox.setText("")
        self.datetimebox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.datetimebox.setScaledContents(True)
        self.datetimebox.setObjectName("datetimebox")
        self.miscellaneousbox = QtWidgets.QLabel(self.centralwidget)
        self.miscellaneousbox.setGeometry(QtCore.QRect(1380, 130, 511, 151))
        self.miscellaneousbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.miscellaneousbox.setText("")
        self.miscellaneousbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.miscellaneousbox.setScaledContents(True)
        self.miscellaneousbox.setObjectName("miscellaneousbox")
        self.tempbox = QtWidgets.QLabel(self.centralwidget)
        self.tempbox.setGeometry(QtCore.QRect(1070, 10, 301, 111))
        self.tempbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.tempbox.setText("")
        self.tempbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.tempbox.setScaledContents(True)
        self.tempbox.setObjectName("tempbox")
        self.jarvisbox = QtWidgets.QLabel(self.centralwidget)
        self.jarvisbox.setGeometry(QtCore.QRect(1380, 10, 251, 81))
        self.jarvisbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.jarvisbox.setText("")
        self.jarvisbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.jarvisbox.setScaledContents(True)
        self.jarvisbox.setObjectName("jarvisbox")
        self.databasestatusbox = QtWidgets.QLabel(self.centralwidget)
        self.databasestatusbox.setGeometry(QtCore.QRect(1640, 10, 251, 81))
        self.databasestatusbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.databasestatusbox.setText("")
        self.databasestatusbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.databasestatusbox.setScaledContents(True)
        self.databasestatusbox.setObjectName("databasestatusbox")
        self.shutbox = QtWidgets.QLabel(self.centralwidget)
        self.shutbox.setGeometry(QtCore.QRect(1640, 920, 251, 81))
        self.shutbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.shutbox.setText("")
        self.shutbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.shutbox.setScaledContents(True)
        self.shutbox.setObjectName("shutbox")
        self.triggerbox = QtWidgets.QLabel(self.centralwidget)
        self.triggerbox.setGeometry(QtCore.QRect(1640, 820, 251, 81))
        self.triggerbox.setStyleSheet("font: 81 14pt \"Rockwell Extra Bold\";")
        self.triggerbox.setText("")
        self.triggerbox.setPixmap(QtGui.QPixmap("GUI images/d8oq3pw-f464437c-92a3-49f3-ba8e-bbfd3d52f543.png"))
        self.triggerbox.setScaledContents(True)
        self.triggerbox.setObjectName("triggerbox")
        self.triggerjarvis = QtWidgets.QPushButton(self.centralwidget)
        self.triggerjarvis.setGeometry(QtCore.QRect(1670, 830, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.triggerjarvis.setFont(font)
        self.triggerjarvis.setAutoFillBackground(False)
        self.triggerjarvis.setStyleSheet("background-color: transparent;\n"
"font: 81 14pt \"Rockwell Extra Bold\";\n"
"color: rgb(85, 255, 0);")
        self.triggerjarvis.setObjectName("triggerjarvis")
        self.datetime = QtWidgets.QTextBrowser(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(630, 30, 301, 51))
        self.datetime.setStyleSheet("background-color:transparent;\n"
"border-radius: none;\n"
"font: 81 28pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.datetime.setObjectName("datetime")
        self.temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(1080, 30, 271, 61))
        self.temp.setStyleSheet("background-color:transparent;\n"
"border-radius: none;\n"
"font: 81 14pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.temp.setObjectName("temp")
        self.jarvisstatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.jarvisstatus.setGeometry(QtCore.QRect(1390, 20, 221, 41))
        self.jarvisstatus.setStyleSheet("background-color:transparent;\n"
"border-radius: none;\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.jarvisstatus.setObjectName("jarvisstatus")
        self.databasestatus = QtWidgets.QTextBrowser(self.centralwidget)
        self.databasestatus.setGeometry(QtCore.QRect(1650, 20, 221, 41))
        self.databasestatus.setStyleSheet("background-color:transparent;\n"
"border-radius: none;\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.databasestatus.setObjectName("databasestatus")
        self.miscellaneous = QtWidgets.QTextBrowser(self.centralwidget)
        self.miscellaneous.setGeometry(QtCore.QRect(1400, 150, 461, 101))
        self.miscellaneous.setStyleSheet("background-color:transparent;\n"
"border-radius: none;\n"
"font: 81 8pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.miscellaneous.setObjectName("miscellaneous")
        self.triggerjarvis_2 = QtWidgets.QPushButton(self.centralwidget)
        self.triggerjarvis_2.setGeometry(QtCore.QRect(1770, 70, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.triggerjarvis_2.setFont(font)
        self.triggerjarvis_2.setAutoFillBackground(False)
        self.triggerjarvis_2.setStyleSheet("background-color: transparent;\n"
"font: 81 11pt \"Rockwell Extra Bold\";\n"
"color: rgb(255, 0, 127);")
        self.triggerjarvis_2.setObjectName("triggerjarvis_2")
        self.triggerjarvis_3 = QtWidgets.QPushButton(self.centralwidget)
        self.triggerjarvis_3.setGeometry(QtCore.QRect(1510, 70, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.triggerjarvis_3.setFont(font)
        self.triggerjarvis_3.setAutoFillBackground(False)
        self.triggerjarvis_3.setStyleSheet("background-color: transparent;\n"
"font: 81 11pt \"Rockwell Extra Bold\";\n"
"color: rgb(255, 0, 0);")
        self.triggerjarvis_3.setObjectName("triggerjarvis_3")
        self.triggerjarvis_4 = QtWidgets.QPushButton(self.centralwidget)
        self.triggerjarvis_4.setGeometry(QtCore.QRect(790, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.triggerjarvis_4.setFont(font)
        self.triggerjarvis_4.setAutoFillBackground(False)
        self.triggerjarvis_4.setStyleSheet("background-color: transparent;\n"
"font: 81 11pt \"Rockwell Extra Bold\";\n"
"color: rgb(0, 255, 0);")
        self.triggerjarvis_4.setObjectName("triggerjarvis_4")
        self.triggerjarvis_5 = QtWidgets.QPushButton(self.centralwidget)
        self.triggerjarvis_5.setGeometry(QtCore.QRect(1220, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.triggerjarvis_5.setFont(font)
        self.triggerjarvis_5.setAutoFillBackground(False)
        self.triggerjarvis_5.setStyleSheet("background-color: transparent;\n"
"font: 81 11pt \"Rockwell Extra Bold\";\n"
"color: rgb(255, 255, 0);")
        self.triggerjarvis_5.setObjectName("triggerjarvis_5")
        self.backgroud.raise_()
        self.initialising.raise_()
        self.voice.raise_()
        self.miscellaneousbox.raise_()
        self.tempbox.raise_()
        self.jarvisbox.raise_()
        self.databasestatusbox.raise_()
        self.shutbox.raise_()
        self.shutengine.raise_()
        self.triggerbox.raise_()
        self.triggerjarvis.raise_()
        self.datetimebox.raise_()
        self.datetime.raise_()
        self.jarvisstatus.raise_()
        self.databasestatus.raise_()
        self.miscellaneous.raise_()
        self.temp.raise_()
        self.triggerjarvis_2.raise_()
        self.triggerjarvis_3.raise_()
        self.triggerjarvis_4.raise_()
        self.triggerjarvis_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backgroud.setStyleSheet(_translate("MainWindow", "background:transparent;\n"
"border:none;"))
        self.shutengine.setText(_translate("MainWindow", "SHUT ENGINE"))
        self.triggerjarvis.setText(_translate("MainWindow", "TRIGGER JARVIS"))
        self.triggerjarvis_2.setText(_translate("MainWindow", "DataBase"))
        self.triggerjarvis_3.setText(_translate("MainWindow", "JARVIS"))
        self.triggerjarvis_4.setText(_translate("MainWindow", "Entry Log Time"))
        self.triggerjarvis_5.setText(_translate("MainWindow", "Temperature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
